openapi: 3.0.3
info:
  description: >-
    The Chia node and services come with a JSON RPC API server that allows you to access information and control the services. 
    These are accessible via HTTPS, WebSockets, or via client SDKs. The ports can be configured in `~/.chia/mainnet/config/config.yaml`. 
    The RPC ports should not be exposed to the internet. TLS certificates are used to secure the communication 
    [using mutualTLS](https://github.com/dkackman/chia-api/wiki/Mutual-TLS).

    The harvester uses port 8560 by default.
  version: 2.1.0
  title: Chia RPC
  termsOfService: https://www.chia.net/assets/legal/Guidelines-for-Using-Chia-Network.pdf
  contact:
    name: Chia Network
    url: https://www.chia.net/
    email: hello@chia.net
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: https://localhost:8560
    description: Harvester RPC
security:
  - bearerAuth: []
components:
  requestBodies:
    empty:
      $ref: "requestBodies/empty.yaml#/empty"
  responses:
    empty:
      $ref: "responses/empty.yaml#/empty"
  schemas:
    connection_info:
      $ref: "schemas/connection_info.yaml#/connection_info"
    harvester_config:
      $ref: "schemas/harvester_config.yaml#/harvester_config"
    k_size:
      $ref: "schemas/k_size.yaml#/k_size"
    plot_info:
      $ref: "schemas/plot_info.yaml#/plot_info"
    apiResponse:
      $ref: "schemas/apiResponse.yaml#/apiResponse"
  securitySchemes:
    bearerAuth:
      $ref: "securitySchemes/bearerAuth.yaml#/bearerAuth"
tags:
  - name: Shared
    description: Methods shared by all services.
  - name: Harvester
    description: The harvester RPC API is exposed, by default, on port 8560 and contains methods for managing plot files and directories.
paths:
  /stop_node:
    post:
      tags:
        - Shared
      summary: Stop the node.
      description: Stop the node.
      operationId: stop_node
      requestBody:
        $ref: "#/components/requestBodies/empty"
      responses:
        "200":
          $ref: "#/components/responses/empty"
  /open_connection:
    post:
      tags:
        - Shared
      summary: Add a connection to another node.
      description: Add a connection to another node.
      operationId: open_connection
      requestBody:
        required: true
        description: the address of the connection
        content:
          application/json:
            schema:
              type: object
              required:
                - ip
                - port
              properties:
                ip:
                  type: string
                  format: ipaddress
                port:
                  type: integer
      responses:
        "200":
          $ref: "#/components/responses/empty"
  /close_connection:
    post:
      tags:
        - Shared
      summary: Removes a connection.
      description: Removes a connection.
      operationId: close_connection
      requestBody:
        required: true
        description: the node id of the connection
        content:
          application/json:
            schema:
              type: object
              required:
                - node_id
              properties:
                node_id:
                  type: string
      responses:
        "200":
          $ref: "#/components/responses/empty"
  /get_connections:
    post:
      tags:
        - Shared
      summary: Retrieve the list of connections.
      description: Retrieve the list of connections.
      operationId: get_connections
      requestBody:
        $ref: "#/components/requestBodies/empty"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - type: object
                    properties:
                      connections:
                        type: array
                        items:
                          $ref: "#/components/schemas/connection_info"
                  - $ref: "#/components/schemas/apiResponse"
  /healthz:
    post:
      tags:
        - Shared
      summary: Heartbeat.
      description: Heartbeat.
      operationId: healthz
      requestBody:
        $ref: "#/components/requestBodies/empty"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/apiResponse"
  /get_routes:
    post:
      tags:
        - Shared
      summary: Retrieve the list of routes exposed by the service.
      description: Retrieve the list of routes/endpoints exposed by the service.
      operationId: get_routes
      requestBody:
        $ref: "#/components/requestBodies/empty"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - type: object
                    properties:
                      routes:
                        type: array
                        items:
                          type: string
                  - $ref: "#/components/schemas/apiResponse"
  /add_plot_directory:
    post:
      tags:
        - Harvester
      summary: Add a plot directory to the harvester configuration.
      description: Add a plot directory to the harvester configuration.
      operationId: add_plot_directory
      requestBody:
        description: The directory name to add
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - dirname
              properties:
                dirname:
                  type: string
      responses:
        "200":
          $ref: "#/components/responses/empty"
  /remove_plot_directory:
    post:
      tags:
        - Harvester
      summary: Removes a plot directory from the harvester configuration.
      description: Removes a plot directory from the harvester configuration.
      operationId: remove_plot_directory
      requestBody:
        description: The directory name to remove
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - dirname
              properties:
                dirname:
                  type: string
      responses:
        "200":
          $ref: "#/components/responses/empty"
  /get_plot_directories:
    post:
      tags:
        - Harvester
      summary: Get the list of plot directories from the harvester configuration.
      description: Get the list of plot directories from the harvester configuration.
      operationId: get_plot_directories
      requestBody:
        $ref: "#/components/requestBodies/empty"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - type: object
                    properties:
                      directories:
                        type: array
                        items:
                          type: string
                  - $ref: "#/components/schemas/apiResponse"
  /refresh_plots:
    post:
      tags:
        - Harvester
      summary: Refresh the list of plots.
      description: Refresh the list of plots.
      operationId: refresh_plots
      requestBody:
        $ref: "#/components/requestBodies/empty"
      responses:
        "200":
          $ref: "#/components/responses/empty"
  /get_plots:
    post:
      tags:
        - Harvester
      summary: Get information about the plots the harvester knows about.
      description: Get information about the plots the harvester knows about.
      operationId: get_plots
      requestBody:
        $ref: "#/components/requestBodies/empty"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - type: object
                    properties:
                      failed_to_open_filenames:
                        type: array
                        items:
                          type: string
                      not_found_filenames:
                        type: array
                        items:
                          type: string
                      plots:
                        type: array
                        items:
                          $ref: "#/components/schemas/plot_info"
                  - $ref: "#/components/schemas/apiResponse"
  /delete_plot:
    post:
      tags:
        - Harvester
      summary: Permanently delete a plot file.
      description: Permanently delete a plot file.
      operationId: delete_plot
      requestBody:
        required: true
        description: the file name of the plot
        content:
          application/json:
            schema:
              type: object
              required:
                - filename
              properties:
                filename:
                  type: string
            example:
              filename: plot-k33-2021-06-12-03-55-1d5a2afe637578d6c9dfa04484854831012b678921a8dce5a8aee9c0fd3c1470.plot
      responses:
        "200":
          $ref: "#/components/responses/empty"
  /get_harvester_config:
    post:
      tags:
        - Harvester
      summary: Gets harvester configuration.
      description: Gets harvester configuration.
      operationId: get_harvester_config
      requestBody:
        $ref: "#/components/requestBodies/empty"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/harvester_config"
                  - $ref: "#/components/schemas/apiResponse"
  /update_harvester_config:
    post:
      tags:
        - Harvester
      summary: Updates the harvester configuration.
      description: Updates the harvester configuration.
      operationId: update_harvester_config
      requestBody:
        description: Config details
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/harvester_config"
      responses:
        "200":
          $ref: "#/components/responses/empty"
externalDocs:
  description: Find out more about chia
  url: https://chia.net
